### ISSUE TITLE
Issues since upgrading to Android 13

### ISSUE THREAD

**Issue by MagikGimp** [henrichg/PhoneProfilesPlus#101]
Firstly, thank you for this app; it really is very useful for those of us still used to a function more common with older phones.
My phone upgraded to Android 13 at the end of last year and immediately I noticed a change in behaviour with PPP. Some quirks did seem to iron themselves out over time but screen brightness is still a gripe for me. My Home settings have it set to 90 but it goes to 100 every time and likewise Night mode is set to 3 or something and it goes to far higher than that. I put it at 3 in an attempt to force it dimmer even.
I also struggle with setting volume levels for timers (but that might be just be due to my lack of understanding of how this works as alarms are fine) and have noticed that PPP can turn my mobile Internet off even though my device is not rooted... even though the documentation says this is not possible! But I like this anomaly so I would rather this didn't change! But yes, the brightness problem is my main issue as this was not happening on Android 12.
Again, thank you and I hope this is useful.

**Comment by henrichg** [comment]
For first. Write me, mobile, Android version, PPP version.

Brightness: yes maybe in Android 13 for your device is brightness chsnged. Max. value, linear or exponential levels. But is possible to fix it.

Volumes: sorry, I don't understand,what is problem. In Android since version 1 are channels for volumes. Ringing, notifications, media, alarm (alarm clock), system (system tones), ... Which channel not working good?

Internet: again, I do not understand. Which internet? Over mobile data, Wi-Fi? Switche mobile data on/off requires root. Wi-Fi not.

**Comment by henrichg** [comment]
- Volume level for timers: Your Clock application maybe using notification for this. You must increase in profile "Notification volume". For timers is not used "Alarm volume". And in Android API do not exists volume channel for timers.
- "The slider turns off but the mobile internet is still turned on. It is only temporarily deactivated while WiFi is connected (not what I want, sadly)."
What is "slider" for Wi-Fi? In PPP is possible only switch Wi-Fi on/off. It is the same as in device Settings and Quick tile at top of notificaiton panel.

**Comment by MagikGimp** [comment]
By "slider" I mean the on/off switch. I can use PPP to launch the mobile Internet settings when I switch profiles and it can change the slider to off even though the setting is still on (as my device is not rooted). Don't worry about it. I am fine with this.

Thanks for the info about alarm volumes; I'll look into it. Looking forward to future updates to PPP! Cheers!

**Comment by henrichg** [comment]
"By "slider" I mean the on/off switch. I can use PPP to launch the mobile Internet settings when I switch profiles and it can change the slider to off even though the setting is still on (as my device is not rooted). Don't worry about it. I am fine with this."

You mean profile parameter "Radios"/"(I) Mobile data preference"? Yes this is only option, when device is not rooted. But this displays device Settings "SIM cards & mobile networks" (in my Redmi Note 9 Pro, MIUI 13, Android 12). How is displayed in this screen "Mobile data" is MIUI "problem", not PPP.

Is posible, switch mobile data off and use Wi-Fi. Also is possible to switch Wi-Fo off and use mobile data. This is normal Android behaviour. But maybe is bug in MIUI 14, if is, for short time disabled network, after switch mobile data or Wi-Fi.

**Comment by henrichg** [comment]
Ach so, maybe I understand your problem.
When mobile data are disabled and you switch Wi-Fi off, yes, internet not working, because is disabled both moble data and Wi-Fi. Also, when Wi-Fi is disabled and you switch mobile data off, again is internet disabled.

For this situation is solution:
Keep mobile data on all the time and switch only Wi-Fi on/off. Because used is Wi-Fi even when mobile data is on. Wi-Fi has higher priority. This is normal behaviour in Android.
