### ISSUE TITLE
Vibration control without root on Android 6.0+ devices

### ISSUE THREAD

**Issue by pstarek** [henrichg/PhoneProfilesPlus#13]
Hi,

why this super app needs root access for vibration control (respective ring mode settings)? I have installed another profile app (Profile Widget) and this app controls vibration without root perfectly on my unrooted Honor 7 Lite with Android 6.

**Comment by henrichg** [comment]
Beause this: [stackoverflow.com](http://stackoverflow.com/questions/33071758/you-cannot-change-private-secure-settings-how-to-toggle-ringtone-vibration-i)

But maybe is fixed in Android N. I will test it.: [code.google.com](https://code.google.com/p/android/issues/detail?id=194376&can=4&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened)

**Comment by pstarek** [comment]
Thanks for answer.
