### ISSUE TITLE
Optimize power consumption

### ISSUE THREAD

**Issue by Dre-OS** [henrichg/PhoneProfilesPlus#55]
Is there a way to reduce the battery consumption of PPP? My System detects high power consumption while PPP is in background.

**Comment by henrichg** [comment]
Currently I' working on it. Maybe I reduced it but testing it with "big call test" :-D. 
Also do testing another user data for this.
If you want install this beta. In it is some battery consumption reduction: 
https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
New update, also for battery optimizations: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
Maybe problem is with this:

....
2020-08-28 19:34:32.196 18607-18737/sk.henrichg.phoneprofilesplus E/[OBSERVER CALL] ContactsContentObserver.onChange: uri=content://com.android.contacts
2020-08-28 19:34:32.314 18607-18737/sk.henrichg.phoneprofilesplus E/[OBSERVER CALL] ContactsContentObserver.onChange: uri=content://com.android.contacts
2020-08-28 19:34:32.413 18607-18737/sk.henrichg.phoneprofilesplus E/[OBSERVER CALL] ContactsContentObserver.onChange: uri=content://com.android.contacts
2020-08-28 19:35:32.509 18607-18902/sk.henrichg.phoneprofilesplus E/[WORKER CALL]  ContactsContentObserverWorker.doWork: xxxx

More and more and more changes of contacts from system.

By me, Samsung OneUI system change contacts database in doses. Several contacts each minute. But for each change is sent observer onChange() :-(
In PPP is, for this reason, implemnted call of event handler each minute, not for each onChange()

**Comment by Dre-OS** [comment]
I noticed something, sometimes some profiles turn into manually activated ones (M) even though i did not set them to do that, it just did that after the update you sent me

**Comment by henrichg** [comment]
Also in "Activity log" is log about this? About manual profile activation? Because manual profile activation can be invoked only by click into profile in Activator, in Editor from profile item menu, click into shortcut to profile (shortcut in home or in dynamic menu when you long click home launcher icon) or when is configured in event manual profile activation.

**Comment by henrichg** [comment]
Because you have disabled "Confirm activating profile". This may be problem. You click profile activation without needing confirm it. ;-)

**Comment by Dre-OS** [comment]
> Because you have disabled "Confirm activating profile". This may be problem. You click profile activation without needing confirm it. ;-)
> Och sorry, data in my Pixel are not you, but another user. Sorry. :-) Then please check in your settings this parameter.

Oh, I did deactivate that on purpose as to let a profile stay activated while deactivating some functions that is needed to trigger the event to save power (like the orientation sensor in PPP and turning off the screen) 

My main concern is the other events that i did not set to be manually activated automatically, it makes the currently activated profile (event-activated) turns into a manual one without setting it to act like its manual (M)

**Comment by henrichg** [comment]
Event do not activate profiles manually. Only when you using in event: "Start of event"/"Other parameters"/"[M] Manual proflle activation".
You must check in "Activity log", when is profile activated manually. If it is from event, look at its parameters. Maybe you have enabled manual profile activation for it. Is possible to check it, because profile activation from event is marked as "profile activation from event 1[1]" (count of profiles (count of events)) with data "profile name [event name]".

**Comment by henrichg** [comment]
Check manually activated profile. In "Activity log" is, when will be activated and from which event.

**Comment by henrichg** [comment]
How about battery consumption in latest version? I'm fixed more and more battery drain in PPP.

**Comment by Dre-OS** [comment]
Currently updated and testing, I'll update you if i encounter any power drains detected by my device or any other bugs, thank you : D
