### ISSUE TITLE
Honor 8 brightness and adaptive settings not kept after screen off/on

### ISSUE THREAD

**Issue by CastagnaIT** [henrichg/PhoneProfilesPlus#78]
First of all thank you for this very useful app,
i use this app from several years but lately i have a problem with brightness settings
i have no idea where the problem come from, if someone can enlighten me
![immagine](https://user-images.githubusercontent.com/3257156/141615635-2583da87-2d2b-4e4e-9944-1a0186e01044.png)

I have a profile set in this way:
Profile night:
- adaptive disabled
- brightness level to 0

all other profiles with adaptive enabled.

What happens, example:
Initially i have a profile with adaptive enabled, then:
If i enable the "profile night", initially the settings in the system settings are changed correctly
but every time when i turn off the display, and turn on again, the settings are restored to the previous
(e.g. adaptive will be enabled again and OFC brightness level return to the middle)
then every time that i turn off/on the display i have to reselect the "profile night" to apply again the brightness settings.
(this happens also in revered order profile selection)

**Comment by henrichg** [comment]
Please send me your PPP Settings. For this is in Editor menu Support/E-mail
settings to author.
Thank you.

Dňa so 13. 11. 2021, 11:58 Stefano Gottardo ***@***.***>
napísal(a):

**Comment by CastagnaIT** [comment]
Attached here:
Dispositivo: FRD-L09 (FRD-L09) 
Versione Android: 8.0.0 
[ExportedData.zip](https://github.com/henrichg/PhoneProfilesPlus/files/7533395/ExportedData.zip)

**Comment by henrichg** [comment]
Hm this must be "feature" in Honor. Because, settings saved by PPP (called is standard Android API for this) are not force saved to Honor specific internal settings. And for this reason, Honor restore force saved (changed by user in brightness settings), when screen gets on, not saved by standard Android API. Sorry.
I'm tested it in my Galaxy S21 and working good. Brightness saved by PPP is not changed after screen off and on.

**Comment by CastagnaIT** [comment]
have you a kind of custom handling by brand/model in this project to fix problems for specifics cases?
maybe could be possible to add a security check every time the screen switch on?

**Comment by henrichg** [comment]
In PPP is check for specific devices, Android versions, ...
In your Honor, maybe it is fixed in newer EMUI version. Maybe. I own Honor 7a with Android 8. In it is the same bug.
Is possible to force set brightness to activated profile value, when screen gets on. But then will be ignored changes by user in brightness settings. And this is not good.

**Comment by henrichg** [comment]
OK, maybe fixed. If you want install and test it: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
Maybe solution is force set brightness by activated profile parameters after screen on. But problem is with change of brightness by user in device Settings of quick panel. This change will be replaced by values from activated profile after each screen on.
It is OK for you?

**Comment by CastagnaIT** [comment]
now undestand, it so boring this setting distinctions from EMUI...

for me it could also be fine, but i don't know what judgment all the other users will have
you may need allow this "override" feature as optionally way, some users may not like it

**Comment by henrichg** [comment]
Yes parameter for this is also possible to add. Plaease wait for beta with this workaroud. ;-)

**Comment by CastagnaIT** [comment]
thank you let me know

**Comment by henrichg** [comment]
OK. Install this beta version: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk
In it is reset brightness after screen on to parameters by activated profile.
Option parameter for this workaround will also be added. Currently not exists.

But: you must also configure battery settings for PPP In device Settings/Battery. For more information look at:
https://dontkillmyapp.com/huawei

You must set "App lauch" to "Manage manually". Because, if is set to "Automatic", PPP do not receive SCREEN_ON broadcast. This "Manage manually" is required for all functionality in PPP. EMUI. :-(

**Comment by CastagnaIT** [comment]
thankyou i have just installed and seem to works good

>But: you must also configure battery settings for PPP In device Settings/Battery. For more information look at:
>https://dontkillmyapp.com/huawei

>You must set "App lauch" to "Manage manually". Because, if is set to "Automatic", PPP do not receive SCREEN_ON broadcast. >This "Manage manually" is required for all functionality in PPP. EMUI. :-(

i have not followed these steps, for now works without set them, but maybe i could be wrong
i will test better in the next days

**Comment by henrichg** [comment]
In my Honor 7a, without this configuration ("App lauch" to "Manage manually") will not be received broadcast SCREEN_ON when  PPP is in background (only notification is displayed, not any screen, dialog is displayed, widget is not added to home launcher) and device is not charging. Battery saver in EMUI :-(

**Comment by henrichg** [comment]
How? Working? I have added parameter for enable / disable this. But I must do some additions. Will be do today, tomorrow.

**Comment by CastagnaIT** [comment]
Hi yes, only thing is that after one day EMUI has put the app in "energy saving"
then i have done the mentioned step in battery settings:

> You must set "App lauch" to "Manage manually". 

after that last two days has worked good

**Comment by henrichg** [comment]
New version: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

Added is parameter into PPP Settings. New section "Special profile parameters". In it "Force set brightness at screen on".

**Comment by CastagnaIT** [comment]
from my last comment until today (updated with your last apk 2 day ago) has always worked good

**Comment by henrichg** [comment]
Then good. Fixed. ;-) Will be in next version.
